name: phonon

channels:

  - conda-forge

dependencies:

  # MACE and LAMMPS won't work with python<3.10
  # Latest Python versions could break other dependencies
  - python=3.10

  - notebook>=7.0.0
  - matplotlib
  - numpy<2.0.0
  - scipy

  # Libraries for phonons
  - phonolammps
  - phonopy
  - dynaphopy

  # Install mpi4py via pip to make sure it recognizes
  # the correct backend interface vendor and version
  - pip:
    - mpi4py

